report_interval: 1000

batch_log: True

data_loaders:
  test:
    split_key: test_idxs
    is_graph: True
    drop_last: True 

    pin_memory: False
    seed: null
    num_workers: 4
    batch_size: 10000
    