gpu_list: [] 
master_port: 12355

kind: gnn
launch_wandb: False

defaults:
    - data/dataset: debug_graph_cpu_class_X_time_c_Y_type
    - data/transforms: debug_emu_reg_charge_time_norm_transforms

    - tasks/train: debug_graph_cpu    
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: debug_graph_cpu

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential   
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: resgated_regression_lowenergy_normalization
    - engine: debug_gnn_regresser
    - loss@tasks.train.loss: huber
    - optimizers@tasks.train.optimizers: adam
    - wandb: wandb_config

    
    - _self_