gpu_list: [] 
master_port: 12355

kind: gnn
launch_wandb: True

defaults:
    - data/dataset: vtx_graph
    - data/transforms: emu_reg_charge_time_norm_transforms

    - tasks/train: vtx_train_gnn
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: vtx_evaluate_gnn

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential   
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: resgated_regression_lowenergy_normalization
    - engine: debug_gnn_regresser
    - loss@tasks.train.loss: huber
    - optimizers@tasks.train.optimizers: adam
    - wandb: wandb_config

    
    - _self_