program: /sps/t2k/cehrhardt/Caverns/sweep_run/run_watchmal.sh

method: random #or grid


metric:
  name: val_batch_loss
  goal: minimize

parameters:

  # /data/dataset
  # data-dataset-parameters-config-graph_dataset_path: 
  #   value: /sps/t2k/eleblevec/datasets/graph_datasets/e_mu_500MeV_10each
  # data-dataset-parameters-config-root_file_path: 
  #   value: /sps/t2k/eleblevec/datasets/root_datasets/before_april/e_mu_500MeV_10events_each.root
  # data-dataset-parameters-config-train_keys: 
  #   value: ['time', 'charge']


  # /data/transforms
  # data-transforms-pre_transforms-kNN-k: 
  #   value: 7

  # /model
  # model-dropout: 
  #   values: [0., 0.2, 0.4, 0.6, 0.8, 1]
  # model-conv_in_channels:
  #   values : [[32, 64], [32, 64, 128], [32, 64, 256, 128]]
  # model-linear_out_features:
  #   values: [[128, 32, 4], [128, 64, 32, 4]]
  # model-conv_activation-negative_slope:
  #   values: [0., 0.2, 0.4, 0.6, 0.8, 1]
  model-conv_activation-_target_:
    values: ['torch.nn.Sigmoid', 'torch.nn.LogSoftmax', 'torch.nn.ReLU', 'torch.nn.SiLU', 'torch.nn.SELU']
  model-linear_activation-_target_:
    values: ['torch.nn.Sigmoid', 'torch.nn.LogSoftmax', 'torch.nn.ReLU', 'torch.nn.SiLU', 'torch.nn.SELU']
  # model-norm_method-_target_: 
  #   values: [BatchNorm, GraphNorm, InstanceNorm]

  # /loss
  # tasks-train-loss-delta:
  #   values: [0.01, 0.2, 0.4, 0.6, 0.8, 1]

  # /optimizers
  # tasks-train-optimizers-lr: 
  #   values: [!!float 1e-3, !!float 1e-4, !!float 1e-5]
  
  # /tasks/train
  # tasks-train-val_interval:
  #   values: [5, 10]
  # tasks-train-data_loaders-train-batch_size: 
  #   values: [4096, 2048, 1026, 512]


command:
 - /usr/bin/bash
 - ${program}